
export const RECIPES_LIST_SEARCH = "RECIPES_LIST_SEARCH"
export const RECIPES_ISSEARCHING = "RECIPES_ISSEARCHING"
export const RECIPES_ISSEARCHING_RANDON = "RECIPES_ISSEARCHING_RANDON"
export const RECIPES_CHANGE_SEARCH = "RECIPES_CHANGE_SEARCH"
export const RECIPES_ISDETAILING = "RECIPES_ISDETAILING"
export const RECIPES_LIST_DETAILS  = "RECIPES_LIST_DETAILS"
export const RECIPES_CLEAR_DETAILS = "RECIPES_CLEAR_DETAILS"

export const FAVORITES_ADD = "FAVORITES_ADD"
export const FAVORITES_REMOVE = "FAVORITES_REMOVE"



